/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgCentroConvGUI;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import pkgCentroConvenciones.*;
import static pkgCentroConvenciones.CcApp.cc;

/**
 *
 * @author Win 10
 */
public class FInicio extends javax.swing.JFrame {

    /**
     * Creates new form FInicio
     */
    public FInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntCrearEvento = new javax.swing.JButton();
        bntListaParticipantes = new javax.swing.JButton();
        bntEditarEvento = new javax.swing.JButton();
        bntListaPatrocinadores = new javax.swing.JButton();
        bntListaActividades = new javax.swing.JButton();
        bntListaSalones = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        bntCrearEvento1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CENTRO DE CONVENCIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bntCrearEvento.setText("Crear evento");
        bntCrearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCrearEventoActionPerformed(evt);
            }
        });

        bntListaParticipantes.setText("Lista participantes");
        bntListaParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntListaParticipantesActionPerformed(evt);
            }
        });

        bntEditarEvento.setText("Editar evento");
        bntEditarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarEventoActionPerformed(evt);
            }
        });

        bntListaPatrocinadores.setText("Lista patrocinadoores");
        bntListaPatrocinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntListaPatrocinadoresActionPerformed(evt);
            }
        });

        bntListaActividades.setText("Lista actividades");
        bntListaActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntListaActividadesActionPerformed(evt);
            }
        });

        bntListaSalones.setText("Lista Salones");
        bntListaSalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntListaSalonesActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        bntCrearEvento1.setText("Eliminar evento");
        bntCrearEvento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCrearEvento1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bntCrearEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bntListaSalones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntListaActividades)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntEditarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntListaParticipantes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntListaPatrocinadores)
                            .addComponent(bntCrearEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCrearEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntEditarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCrearEvento1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntListaPatrocinadores)
                            .addComponent(bntListaParticipantes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntListaSalones)
                            .addComponent(bntListaActividades))))
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCrearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCrearEventoActionPerformed
        
        //pasar de ventana
        FCrearEvento fCrearEvento = new FCrearEvento();
        fCrearEvento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntCrearEventoActionPerformed

    private void bntEditarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarEventoActionPerformed
        
        //Debe exisit por los menos un evento para poder acceder a Modificar eventos
        if(CcApp.cc.cantidadEventos() == 0)
        {
            JOptionPane.showMessageDialog(null, "Acceso denegado: debe existir al menos un evento");
        }
        else
        {
            FAdministrarEvento fAdministrarEvento = new FAdministrarEvento();
            fAdministrarEvento.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_bntEditarEventoActionPerformed

    private void bntListaParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListaParticipantesActionPerformed
        
        FListaParticipantes fListaParticipantes = new FListaParticipantes();
        fListaParticipantes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntListaParticipantesActionPerformed

    private void bntListaPatrocinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListaPatrocinadoresActionPerformed
        
        FListaPatrocinadores fListaPatrocinadores = new FListaPatrocinadores();
        fListaPatrocinadores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntListaPatrocinadoresActionPerformed

    private void bntListaSalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListaSalonesActionPerformed
        
        FListaSalones fListaSalones = new FListaSalones();
        fListaSalones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntListaSalonesActionPerformed

    private void bntListaActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListaActividadesActionPerformed
        
        FListaActividades fListaActividades = new FListaActividades();
        fListaActividades.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntListaActividadesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        //guardar datos del archivo
        try
        {
            FileOutputStream fichero = new FileOutputStream("registroCC.txt");
            ObjectOutputStream stream = new ObjectOutputStream(fichero);
            stream.writeObject(cc);
            stream.close();
        }
        catch(FileNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado");
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(null, "Error en stream");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void bntCrearEvento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCrearEvento1ActionPerformed
        
        if(CcApp.cc.cantidadEventos() == 0)
        {
            JOptionPane.showMessageDialog(null, "Acceso denegado: no hay eventos");
        }
        else
        {
            FEliminarEvento fEliminarEvento = new FEliminarEvento();
            fEliminarEvento.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_bntCrearEvento1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FInicio fInicio = new FInicio();
                fInicio.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCrearEvento;
    private javax.swing.JButton bntCrearEvento1;
    private javax.swing.JButton bntEditarEvento;
    private javax.swing.JButton bntListaActividades;
    private javax.swing.JButton bntListaParticipantes;
    private javax.swing.JButton bntListaPatrocinadores;
    private javax.swing.JButton bntListaSalones;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
