/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgCentroConvGUI;

import javax.swing.JOptionPane;
import pkgCentroConvenciones.CcApp;
import pkgCentroConvenciones.Participante;

/**
 *
 * @author Win 10
 */
public class FParticipanteActividad extends javax.swing.JFrame {

    /**
     * Creates new form FParticipanteActividad
     */
    public FParticipanteActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtActividad = new javax.swing.JTextField();
        txtParticipante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Actividad");

        jLabel2.setText("Participante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(74, 74, 74)
                .addComponent(btnGuardar)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(txtActividad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        FAdministrarParticipante fAdministrarParticipante = new FAdministrarParticipante();
        fAdministrarParticipante.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        String actividad = txtActividad.getText();
        int participante = Integer.parseInt(txtParticipante.getText());
        
        //variables para identificar la actividad y al evento al que esta vinculado
        //si no se encuentran el evento o la actividad quedan como -1
        //que es un valor que no pueden recibir como subindice, por lo tanto
        //se puede afirmar que no se encontraron
        int eve = -1;  
        int act = -1;
        
        int p = -1;
        int e = -1;
        
        //for anidado para buscar la actividad y el evento
        for(int i=0; i<CcApp.cc.cantidadEventos(); i++) //loop por cada cantidad de evento
        {
            for(int j=0; j<CcApp.cc.getEvento(i).cantidadActividades(); j++) //buscar en el vector actiividades de cada evento
            {
                if(CcApp.cc.getEvento(i).getActividad(j).getNombre().equals(actividad))
                {
                    eve = i;
                    act = j;
                    System.out.println("j:"+j);
                    break; //si se encontraron, terminar el proceso
                }
            }
        }
        
        //si se encontro la actividad, se manda el mensaje
        if(act == -1)
        {
            JOptionPane.showMessageDialog(null, "No se encontro la actividad");
        }
        else
        {   
            //se compruba que exista el participante y que no este ya vinculado a esa actividad
            for(int i=0; i<CcApp.cc.cantidadEventos(); i++) //loop por cada cantidad de evento
            {
                for(int j=0; j<CcApp.cc.getEvento(i).cantidadParticipantes(); j++) //buscar en el vector actiividades de cada evento
                {
                    if(CcApp.cc.getEvento(i).buscarParticipante(participante) != -1)
                    {
                        e = i;
                        p = j;
                    }
                }
            }
            
            if(p == -1)
            {
                JOptionPane.showMessageDialog(null, "No se encontro el participante");
            }
            else
            {
                //validar que el participante no haya estado vinculado anteriomente
                if(CcApp.cc.getEvento(eve).getActividad(act).buscarParticipante(participante) == -1)
                {                   
                    //si no esta registrado, agregarlo
                    String pn = CcApp.cc.getEvento(e).getParticipante(p).getNombre();
                    int pc    = CcApp.cc.getEvento(e).getParticipante(p).getCodigo();
                    
                    Participante par = new Participante(pn, pc);
                    CcApp.cc.getEvento(eve).getActividad(act).addParticipante(par);
                    
                    int abono    = CcApp.cc.getEvento(eve).getActividad(act).getPrecio();
                    int anterior = CcApp.cc.getEvento(e).getParticipante(p).getCantidadPagar();
                    
                    CcApp.cc.getEvento(e).getParticipante(p).setCantidadPagar(abono + anterior);
                    
                    JOptionPane.showMessageDialog(null, "Se vinculo el participante con exito");
                }
                else
                {
                    //sino, mandar mensaje de que ya existe
                    JOptionPane.showMessageDialog(null, "El participante ya se encuentra vinculado a esa actividad");
                }
            }
            
        }
         
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FParticipanteActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FParticipanteActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FParticipanteActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FParticipanteActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FParticipanteActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtParticipante;
    // End of variables declaration//GEN-END:variables
}
